# 분봉/일봉/주봉/월봉 조회
get_ohlcv 함수
- minute1/minute3/minute5/minute10/minute15/minute30/minute60/minute240
- day/week/month

In [1]:
import pyupbit

In [20]:
# 옵션 설정이 없으면 일별 9시 기준 데이터가 나옴
# 기본이 200개, 최대 200개까지 가져옴. count 를 이용해 갯수를 지정가능 함
df = pyupbit.get_ohlcv('KRW-BTC', interval='minute1', count=100) 
df

,open,high,low,close,volume,value
2023-12-20 20:33:00,58199000.0,58200000.0,58197000.0,58200000.0,1.342544,7.813445e+07
2023-12-20 20:34:00,58200000.0,58200000.0,58190000.0,58192000.0,2.102451,1.223549e+08
2023-12-20 20:35:00,58192000.0,58197000.0,58187000.0,58187000.0,2.550512,1.484203e+08
2023-12-20 20:36:00,58188000.0,58196000.0,58183000.0,58185000.0,1.416873,8.244747e+07
2023-12-20 20:37:00,58185000.0,58197000.0,58178000.0,58180000.0,1.475952,8.587738e+07
...,...,...,...,...,...,...
2023-12-20 22:08:00,58499000.0,58567000.0,58498000.0,58561000.0,22.710549,1.328911e+09
2023-12-20 22:09:00,58561000.0,58658000.0,58560000.0,58649000.0,23.054925,1.351143e+09
2023-12-20 22:10:00,58649000.0,58679000.0,58580000.0,58600000.0,10.480769,6.144713e+08
2023-12-20 22:11:00,58619000.0,58633000.0,58589000.0,58630000.0,10.840219,6.352517e+08
2023-12-20 22:12:00,58633000.0,58642000.0,58628000.0,58640000.0,3.974175,2.330398e+08

# 데이터 샘플링
슬라이싱

In [11]:
# 2분봉을 가져오는 api가 존재하지 않는다. 
#df.iloc[ : : 2] # 2개씩 건너띄도록 출력, 하지만 2분봉은 아님

resample 메서드

In [27]:
# resample("2T") : 00-01, 02-03 그룹화
# apply : 정의된 연산 적용(구제척으로 할 행위)
how = {
    "open" : 'first',
    "high" : max,
    "low" : min,
    "close" : 'last',
    "volume" : sum,
    "value" : sum,
}


df.resample(rule='2T').apply(how)

/var/folders/lm/k5qsdy_x3nj23lk2y853mh9h0000gn/T/ipykernel_94936/2081119205.py:13: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.resample(rule='2T').apply(how)
/var/folders/lm/k5qsdy_x3nj23lk2y853mh9h0000gn/T/ipykernel_94936/2081119205.py:13: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.resample(rule='2T').apply(how)
/var/folders/lm/k5qsdy_x3nj23lk2y853mh9h0000gn/T/ipykernel_94936/2081119205.py:13: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.resample(rule='2T').apply(how)

,open,high,low,close,volume,value
2023-12-20 20:32:00,58199000.0,58200000.0,58197000.0,58200000.0,1.342544,7.813445e+07
2023-12-20 20:34:00,58200000.0,58200000.0,58187000.0,58187000.0,4.652963,2.707752e+08
2023-12-20 20:36:00,58188000.0,58197000.0,58178000.0,58180000.0,2.892826,1.683249e+08
2023-12-20 20:38:00,58180000.0,58200000.0,58180000.0,58198000.0,1.801542,1.048388e+08
2023-12-20 20:40:00,58199000.0,58200000.0,58198000.0,58200000.0,3.893104,2.265757e+08
2023-12-20 20:42:00,58200000.0,58200000.0,58194000.0,58194000.0,6.644521,3.866989e+08
2023-12-20 20:44:00,58194000.0,58200000.0,58178000.0,58195000.0,2.928022,1.704018e+08
2023-12-20 20:46:00,58195000.0,58200000.0,58191000.0,58200000.0,3.819003,2.222568e+08
2023-12-20 20:48:00,58200000.0,58365000.0,58196000.0,58349000.0,15.830040,9.217773e+08
2023-12-20 20:50:00,58342000.0,58400000.0,58317000.0,58322000.0,8.968541,5.234098e+08
2023-12-20 20:52:00,58357000.0,58357000.0,58304000.0,58328000.0,3.548282,2.069338e+08
2023-12-20 20:54:00,58328000.0,58332000.0,58281000.0,58318000.0,4.952930,2.888282e+08
2023-12-20 20:56:00,58303000.0,58314000.0,58272000.0,58278000.0,3.264082,1.902272e+08
2023-12-20 20:58:00,58275000.0,58278000.0,58232000.0,58235000.0,2.778263,1.618736e+08
2023-12-20 21:00:00,58243000.0,58255000.0,58210000.0,58215000.0,3.382780,1.969837e+08
2023-12-20 21:02:00,58214000.0,58248000.0,58214000.0,58223000.0,3.129145,1.822045e+08
2023-12-20 21:04:00,58224000.0,58239000.0,58221000.0,58225000.0,3.123227,1.818700e+08
2023-12-20 21:06:00,58225000.0,58235000.0,58217000.0,58222000.0,3.573143,2.080364e+08
2023-12-20 21:08:00,58222000.0,58222000.0,58198000.0,58200000.0,5.439230,3.166175e+08
2023-12-20 21:10:00,58200000.0,58210000.0,58183000.0,58209000.0,4.118359,2.396967e+08
2023-12-20 21:12:00,58210000.0,58236000.0,58209000.0,58236000.0,6.021891,3.505951e+08
2023-12-20 21:14:00,58237000.0,58300000.0,58233000.0,58259000.0,7.225424,4.209859e+08
2023-12-20 21:16:00,58258000.0,58300000.0,58258000.0,58299000.0,5.030748,2.931966e+08
2023-12-20 21:18:00,58299000.0,58299000.0,58271000.0,58297000.0,3.956924,2.306179e+08
2023-12-20 21:20:00,58298000.0,58309000.0,58265000.0,58308000.0,3.014346,1.757321e+08
2023-12-20 21:22:00,58308000.0,58310000.0,58254000.0,58310000.0,6.009448,3.502243e+08
2023-12-20 21:24:00,58309000.0,58321000.0,58308000.0,58318000.0,4.811049,2.805363e+08
2023-12-20 21:26:00,58318000.0,58330000.0,58308000.0,58330000.0,5.699998,3.324385e+08
2023-12-20 21:28:00,58316000.0,58316000.0,58308000.0,58309000.0,4.760908,2.776063e+08
2023-12-20 21:30:00,58309000.0,58330000.0,58277000.0,58288000.0,4.487206,2.615787e+08
2023-12-20 21:32:00,58288000.0,58328000.0,58277000.0,58315000.0,4.578428,2.669428e+08
2023-12-20 21:34:00,58295000.0,58330000.0,58295000.0,58329000.0,3.236463,1.887289e+08
2023-12-20 21:36:00,58329000.0,58364000.0,58315000.0,58364000.0,5.389352,3.144030e+08
2023-12-20 21:38:00,58365000.0,58369000.0,58334000.0,58365000.0,12.657375,7.386229e+08
2023-12-20 21:40:00,58334000.0,58364000.0,58320000.0,58363000.0,4.179869,2.439139e+08
2023-12-20 21:42:00,58363000.0,58363000.0,58313000.0,58328000.0,4.164506,2.429446e+08
2023-12-20 21:44:00,58329000.0,58357000.0,58311000.0,58356000.0,4.095048,2.388649e+08
2023-12-20 21:46:00,58356000.0,58364000.0,58309000.0,58324000.0,5.988705,3.493318e+08
2023-12-20 21:48:00,58314000.0,58345000.0,58314000.0,58332000.0,4.810542,2.805755e+08
2023-12-20 21:50:00,58332000.0,58365000.0,58325000.0,58365000.0,4.094172,2.388538e+08
2023-12-20 21:52:00,58365000.0,58404000.0,58365000.0,58399000.0,5.628144,3.286058e+08
2023-12-20 21:54:00,58399000.0,58405000.0,58397000.0,58405000.0,4.691663,2.739999e+08
2023-12-20 21:56:00,58402000.0,58413000.0,58401000.0,58411000.0,2.036749,1.189591e+08
2023-12-20 21:58:00,58411000.0,58447000.0,58411000.0,58446000.0,9.861038,5.761086e+08
2023-12-20 22:00:00,58446000.0,58483000.0,58434000.0,58483000.0,11.833506,6.917382e+08
2023-12-20 22:02:00,58483000.0,58495000.0,58460000.0,58461000.0,17.314414,1.012659e+09
2023-12-20 22:04:00,58461000.0,58500000.0,58450000.0,58499000.0,10.832893,6.334511e+08
2023-12-20 22:06:00,58499000.0,58500000.0,58456000.0,58499000.0,11.024331,6.448370e+08
2023-12-20 22:08:00,58499000.0,58658000.0,58498000.0,58649000.0,45.765474,2.680054e+09
2023-12-20 22:10:00,58649000.0,58679000.0,58580000.0,58630000.0,21.320988,1.249723e+09
2023-12-20 22:12:00,58633000.0,58642000.0,58628000.0,58640000.0,3.974175,2.330398e+08

In [28]:
df.head(5)

,open,high,low,close,volume,value
2023-12-20 20:33:00,58199000.0,58200000.0,58197000.0,58200000.0,1.342544,7.813445e+07
2023-12-20 20:34:00,58200000.0,58200000.0,58190000.0,58192000.0,2.102451,1.223549e+08
2023-12-20 20:35:00,58192000.0,58197000.0,58187000.0,58187000.0,2.550512,1.484203e+08
2023-12-20 20:36:00,58188000.0,58196000.0,58183000.0,58185000.0,1.416873,8.244747e+07
2023-12-20 20:37:00,58185000.0,58197000.0,58178000.0,58180000.0,1.475952,8.587738e+07

In [31]:
# 무조건 200개만 가져오기 때문에 to 옵션을 사용해서 마지막 날짜를 지정할 수 있다.
# 결과값은 무조건 하루전기준부터 200개 데이터를 가져온다. 20200827
df = pyupbit.get_ohlcv('KRW-BTC', to="20200828")
df

,open,high,low,close,volume,value
2020-02-10 09:00:00,11821000.0,11864000.0,11392000.0,11520000.0,5213.484235,6.045989e+10
2020-02-11 09:00:00,11520000.0,11950000.0,11269000.0,11819000.0,6034.791223,6.998445e+10
2020-02-12 09:00:00,11820000.0,11956000.0,11761000.0,11793000.0,6619.138190,7.834158e+10
2020-02-13 09:00:00,11793000.0,12044000.0,11580000.0,11793000.0,9190.663960,1.085602e+11
2020-02-14 09:00:00,11793000.0,11899000.0,11717000.0,11845000.0,4420.813842,5.224741e+10
...,...,...,...,...,...,...
2020-08-23 09:00:00,13850000.0,13856000.0,13700000.0,13802000.0,2120.583340,2.921457e+10
2020-08-24 09:00:00,13816000.0,13940000.0,13745000.0,13876000.0,3402.101195,4.714093e+10
2020-08-25 09:00:00,13876000.0,13884000.0,13341000.0,13476000.0,5630.219385,7.668247e+10
2020-08-26 09:00:00,13473000.0,13633000.0,13350000.0,13561000.0,7348.775059,9.921504e+10
2020-08-27 09:00:00,13561000.0,13675000.0,13245000.0,13401000.0,5462.363708,7.337273e+10

In [33]:
!pip install pandas

Requirement already satisfied: pandas in /Users/tintoll/anaconda3/lib/python3.11/site-packages (2.1.1)
Requirement already satisfied: numpy>=1.23.2 in /Users/tintoll/anaconda3/lib/python3.11/site-packages (from pandas) (1.26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/tintoll/anaconda3/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/tintoll/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Users/tintoll/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /Users/tintoll/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [43]:
import pandas as pd
import time

In [45]:
# 원하는 날짜의 데이터 가져오기 
start = "20190101"
last = "20210101"

# 다음날짜를 쉽게 가져오기 위해서 datetime으로 변환
last = pd.to_datetime(last)
# 하루를 더해준다.
last = last + pd.Timedelta(days=1) 

dfs = []

while True:
    df = pyupbit.get_ohlcv('KRW-BTC', to=last)
    last = df.index[0] # 제일처음인덱스값으로 다시 조회
    
    dfs.append(df)
    
    if start in df.index:
        break
    time.sleep(0.1) # api 사용한도로 인해서 지연을 줌.
dfs

[                           open        high         low       close  \
 2020-06-16 09:00:00  11339000.0  11492000.0  11267000.0  11453000.0
 2020-06-17 09:00:00  11453000.0  11517000.0  11320000.0  11437000.0
 2020-06-18 09:00:00  11437000.0  11445000.0  11224000.0  11341000.0
 2020-06-19 09:00:00  11341000.0  11382000.0  11150000.0  11286000.0
 2020-06-20 09:00:00  11285000.0  11351000.0  11155000.0  11325000.0
 ...                         ...         ...         ...         ...
 2020-12-28 09:00:00  29347000.0  30587000.0  29167000.0  30249000.0
 2020-12-29 09:00:00  30219000.0  30520000.0  29028000.0  30498000.0
 2020-12-30 09:00:00  30498000.0  31999000.0  30333000.0  31891000.0
 2020-12-31 09:00:00  31923000.0  32386000.0  31300000.0  32042000.0
 2021-01-01 09:00:00  32037000.0  32599000.0  31800000.0  32296000.0

                            volume         value
 2020-06-16 09:00:00   3026.568243  3.450289e+10
 2020-06-17 09:00:00   2739.255456  3.123835e+10
 2020-06-18 09:00:00   2323.411973  2.638181e+10
 2020-06-19 09:00:00   2389.517785  2.694653e+10
 2020-06-20 09:00:00   1263.732900  1.423141e+10
 ...                           ...           ...
 2020-12-28 09:00:00   8175.159923  2.455058e+11
 2020-12-29 09:00:00   7302.220616  2.180911e+11
 2020-12-30 09:00:00  10282.822805  3.209409e+11
 2020-12-31 09:00:00   8041.248074  2.567653e+11
 2021-01-01 09:00:00   5752.494216  1.856139e+11

 [200 rows x 6 columns],
                            open        high         low       close  \
 2019-11-30 09:00:00   9035000.0   9106000.0   8726000.0   8838000.0
 2019-12-01 09:00:00   8838000.0   8840000.0   8480000.0   8630000.0
 2019-12-02 09:00:00   8630000.0   8705000.0   8415000.0   8585000.0
 2019-12-03 09:00:00   8590000.0   8700000.0   8520000.0   8607000.0
 2019-12-04 09:00:00   8607000.0   8996000.0   8432000.0   8515000.0
 ...                         ...         ...         ...         ...
 2020-06-12 09:00:00  11090000.0  11449000.0  11062000.0  11380000.0
 2020-06-13 09:00:00  11374000.0  11406000.0  11272000.0  11388000.0
 2020-06-14 09:00:00  11382000.0  11395000.0  11156000.0  11246000.0
 2020-06-15 09:00:00  11246000.0  11415000.0  10770000.0  11346000.0
 2020-06-16 09:00:00  11339000.0  11492000.0  11267000.0  11453000.0

                           volume         value
 2019-11-30 09:00:00  2495.787933  2.230524e+10
 2019-12-01 09:00:00  3023.698278  2.606601e+10
 2019-12-02 09:00:00  1837.439258  1.571477e+10
 2019-12-03 09:00:00  1641.815953  1.414423e+10
 2019-12-04 09:00:00  5171.381015  4.477820e+10
 ...                          ...           ...
 2020-06-12 09:00:00  2651.817380  3.002331e+10
 2020-06-13 09:00:00  1212.950409  1.377168e+10
 2020-06-14 09:00:00  1408.073502  1.590881e+10
 2020-06-15 09:00:00  4693.793931  5.201435e+10
 2020-06-16 09:00:00  3026.568243  3.450289e+10

 [200 rows x 6 columns],
                           open       high        low      close        volume  \
 2019-05-15 09:00:00  9499000.0  9757000.0  9220000.0  9606000.0  17857.086359
 2019-05-16 09:00:00  9606000.0  9842000.0  9247000.0  9465000.0  17057.027562
 2019-05-17 09:00:00  9465000.0  9557000.0  8360000.0  8891000.0  22071.335651
 2019-05-18 09:00:00  8891000.0  9232000.0  8684000.0  8823000.0  11615.277001
 2019-05-19 09:00:00  8819000.0  9809000.0  8810000.0  9712000.0  16388.299831
 ...                        ...        ...        ...        ...           ...
 2019-11-26 09:00:00  8338000.0  8627000.0  8240000.0  8410000.0   5867.688767
 2019-11-27 09:00:00  8413000.0  8900000.0  8041000.0  8702000.0   9265.752231
 2019-11-28 09:00:00  8700000.0  8903000.0  8615000.0  8674000.0   4045.723910
 2019-11-29 09:00:00  8672000.0  9200000.0  8658000.0  9037000.0   4210.800500
 2019-11-30 09:00:00  9035000.0  9106000.0  8726000.0  8838000.0   2495.787933

                             value
 2019-05-15 09:00:00  1.698520e+11
 2019-05-16 09:00:00  1.634953e+11
 2019-05-17 09:00:00  1.934770e+11
 2019-05-18 09:00:00  1.035323e+11
 2019-05-19 09:00:00  1.545847e+11
 ...                           ...
 2019-11-26 09:00:00  4.937402e+10
 2019-11-27 09:00:00  7.803678e+10
 2019-11-28 09:00:00  3.538489e+10
 2019-11-29 09:00:00  3.763841e+10
 2019-11-30 09:00:00  2.230524e+10

 [200 rows x 6 columns],
                           open       high        low      close        volume  \
 2018-10-28 09:00:00  7284000.0  7290000.0  7241000.0  7258000.0   1367.837482
 2018-10-29 09:00:00  7259000.0  7264000.0  7057000.0  7097000.0   3760.907316
 2018-10-30 09:00:00  7097000.0  7162000.0  7094000.0  7140000.0   2329.379782
 2018-10-31 09:00:00  7139000.0  7200000.0  7062000.0  7162000.0   2918.684467
 2018-11-01 09:00:00  7162000.0  7200000.0  7141000.0  7186000.0   1920.593185
 ...                        ...        ...        ...        ...           ...
 2019-05-11 09:00:00  7495000.0  8551000.0  7491000.0  8368000.0  24016.233181
 2019-05-12 09:00:00  8370000.0  8807000.0  7950000.0  8170000.0  21060.149816
 2019-05-13 09:00:00  8166000.0  9518000.0  8064000.0  9230000.0  26618.706357
 2019-05-14 09:00:00  9235000.0  9907000.0  9100000.0  9499000.0  25056.334457
 2019-05-15 09:00:00  9499000.0  9757000.0  9220000.0  9606000.0  17857.086359

                             value
 2018-10-28 09:00:00  9.933433e+09
 2018-10-29 09:00:00  2.696790e+10
 2018-10-30 09:00:00  1.663239e+10
 2018-10-31 09:00:00  2.081816e+10
 2018-11-01 09:00:00  1.375758e+10
 ...                           ...
 2019-05-11 09:00:00  1.922032e+11
 2019-05-12 09:00:00  1.764499e+11
 2019-05-13 09:00:00  2.356440e+11
 2019-05-14 09:00:00  2.386327e+11
 2019-05-15 09:00:00  1.698520e+11

 [200 rows x 6 columns]]

In [46]:
len(dfs)

4

In [49]:
result = pd.concat(dfs).sort_index() # 4개묶여있던 데이터를 하나의 데이터로 변환, 인덱스 기준으로 정렬 해준다.
print(result) # 불필요한 2018년 데이터도 포함되어있다.
print(result.loc[start: ])

                           open        high         low       close  \
2018-10-28 09:00:00   7284000.0   7290000.0   7241000.0   7258000.0
2018-10-29 09:00:00   7259000.0   7264000.0   7057000.0   7097000.0
2018-10-30 09:00:00   7097000.0   7162000.0   7094000.0   7140000.0
2018-10-31 09:00:00   7139000.0   7200000.0   7062000.0   7162000.0
2018-11-01 09:00:00   7162000.0   7200000.0   7141000.0   7186000.0
...                         ...         ...         ...         ...
2020-12-28 09:00:00  29347000.0  30587000.0  29167000.0  30249000.0
2020-12-29 09:00:00  30219000.0  30520000.0  29028000.0  30498000.0
2020-12-30 09:00:00  30498000.0  31999000.0  30333000.0  31891000.0
2020-12-31 09:00:00  31923000.0  32386000.0  31300000.0  32042000.0
2021-01-01 09:00:00  32037000.0  32599000.0  31800000.0  32296000.0

                           volume         value
2018-10-28 09:00:00   1367.837482  9.933433e+09
2018-10-29 09:00:00   3760.907316  2.696790e+10
2018-10-30 09:00:00   2329.379782  1.663239e+10
2018-10-31 09:00:00   2918.684467  2.081816e+10
2018-11-01 09:00:00   1920.593185  1.375758e+10
...                           ...           ...
2020-12-28 09:00:00   8175.159923  2.455058e+11
2020-12-29 09:00:00   7302.220616  2.180911e+11
2020-12-30 09:00:00  10282.822805  3.209409e+11
2020-12-31 09:00:00   8041.248074  2.567653e+11
2021-01-01 09:00:00   5752.494216  1.856139e+11

[800 rows x 6 columns]

,open,high,low,close,volume,value
2019-01-01 09:00:00,4200000.0,4297000.0,4130000.0,4288000.0,3806.560395,1.599756e+10
2019-01-02 09:00:00,4288000.0,4366000.0,4241000.0,4347000.0,5413.333046,2.323826e+10
2019-01-03 09:00:00,4348000.0,4360000.0,4251000.0,4284000.0,4683.662098,2.018933e+10
2019-01-04 09:00:00,4285000.0,4328000.0,4231000.0,4303000.0,5455.729434,2.336545e+10
2019-01-05 09:00:00,4304000.0,4345000.0,4270000.0,4294000.0,3332.948924,1.436761e+10
...,...,...,...,...,...,...
2020-12-28 09:00:00,29347000.0,30587000.0,29167000.0,30249000.0,8175.159923,2.455058e+11
2020-12-29 09:00:00,30219000.0,30520000.0,29028000.0,30498000.0,7302.220616,2.180911e+11
2020-12-30 09:00:00,30498000.0,31999000.0,30333000.0,31891000.0,10282.822805,3.209409e+11
2020-12-31 09:00:00,31923000.0,32386000.0,31300000.0,32042000.0,8041.248074,2.567653e+11
2021-01-01 09:00:00,32037000.0,32599000.0,31800000.0,32296000.0,5752.494216,1.856139e+11

In [58]:
def ohlcv(ticker, start, last):
    # 다음날짜를 쉽게 가져오기 위해서 datetime으로 변환
    last = pd.to_datetime(last)
    # 하루를 더해준다.
    last = last + pd.Timedelta(days=1) 

    dfs = []

    while True:
        df = pyupbit.get_ohlcv(ticker, to=last)
        last = df.index[0] # 제일처음인덱스값으로 다시 조회

        dfs.append(df)

        if start in df.index:
            break
        time.sleep(0.1) # api 사용한도로 인해서 지연을 줌.
    result = pd.concat(dfs).sort_index() # 4개묶여있던 데이터를 하나의 데이터로 변환, 인덱스 기준으로 정렬 해준다.
    return result.loc[start: ]

In [59]:
ohlcv('KRW-BTC','20210101', '20230101')

,open,high,low,close,volume,value
2021-01-01 09:00:00,32037000.0,32599000.0,31800000.0,32296000.0,5752.494216,1.856139e+11
2021-01-02 09:00:00,32295000.0,36600000.0,31920000.0,35700000.0,17451.167678,6.023355e+11
2021-01-03 09:00:00,35700000.0,39453000.0,35500000.0,37537000.0,25381.506623,9.588751e+11
2021-01-04 09:00:00,37537000.0,38476000.0,33000000.0,36460000.0,23598.194590,8.472770e+11
2021-01-05 09:00:00,36478000.0,38590000.0,34357000.0,38093000.0,13461.981681,4.915540e+11
...,...,...,...,...,...,...
2022-12-28 09:00:00,21324000.0,21396000.0,21010000.0,21061000.0,3151.280761,6.675252e+10
2022-12-29 09:00:00,21061000.0,21295000.0,20908000.0,21201000.0,2464.457822,5.197588e+10
2022-12-30 09:00:00,21201000.0,21232000.0,20700000.0,21070000.0,2699.072216,5.657707e+10
2022-12-31 09:00:00,21086000.0,21249000.0,20966000.0,21079000.0,2960.900095,6.253054e+10
2023-01-01 09:00:00,21079000.0,21171000.0,21002000.0,21123000.0,1486.467553,3.135794e+10